### ISSUE TITLE
Establish naming schema for variables

### ISSUE THREAD

**Issue by nyrrad** [Sirikon/cinnamon-spices-website#6]
**We need to establish a naming schema for variables.**

I started using name spacing for non color variables which i think works well, but we need to come up with a naming system for colors.

I'm **REALLY** pushing consistency because although the spices site is small the network of sites will not be.

**Comment by sirikon** [comment]
I agree, we need to stablish this asap.

What about something like this:

```
[type]_[what](_[variation])
```

Any of the names (type, what and variation) should use `-` instead of spaces.

For example:

```
color_background
color_background_darker
font-size_jumbotron
```

For colors, as they are somehow special we could use something like:

```
color__brand
color__assertive
```

(using `__` for more abstract definitions)

Any better ideas?

Whatever we end up choosing, we should centralize the main variables in a single place, will be easier to understand when it's properly organized in a single file.

**Comment by nyrrad** [comment]
I like that for the color schema
For defining colors do we wanna do something like

``` sass
color_gray-1: #111;
color_gray-2: #222;
color_gray-3: #333;
color_gray-4: #444;
```

But you know with the grays we actually use. haha

I feel like we should namespace the component level variables. In-fact with that last PR i did you can see i started doing that.

On the component level i think it should be something like: 

``` sass
component_item_variation
```

> Whatever we end up choosing, we should centralize the main variables in a single place, will be easier to understand when it's properly organized in a single file.

I started doing this in my last PR. Going to keep doing it. :)

**Comment by sirikon** [comment]
Yep, looks perfect for me :)

Anyway, as we use it and see how the codebase grows, we'll be able to do some refactors if needed.

Will keep the issue open a day or two more, just in case someone have something to say, but for me it's done :)

Thanks! :+1:

**Comment by MrElectroNick** [comment]
Regarding flex containers and items
cs-flex {display:flex}
cs-flex-row {display:flex;flex-direction:row}
cs-flex-column {display:flex;flex-direction:column}

Something like this will minimize amount of code in additional stylesheet

**Comment by nyrrad** [comment]
Yea, flex object goo

**Comment by sirikon** [comment]
I'll close the issue, I think the conversation is over now :)
