### ISSUE TITLE
Em's or Rem's for font sizes

### ISSUE THREAD

**Issue by nyrrad** [Sirikon/cinnamon-spices-website#7]
Relative font sizes are superior, particularly when we make the sites responsive

**Comment by sirikon** [comment]
It depends... does the element have a size that depends on the parent's size or it's a "global" size for scaling?

I vote for just using correctly both.

**Comment by MrElectroNick** [comment]
@nyrrad - suggest a case. I fully support relative sizes for fonts in content areas but in some UI cases it will still require to set size in pixels. Anyway I agree

**Comment by nyrrad** [comment]
Honestly i feel like we should do away with pixels all together for all elements.. We can set a base font-size of 16px on the body then use rems on all subsequent elements. Then use em's on modifier classes and headings.

With this method we can still do the precise sizes it will just require a tiny bit of math. I.E 18px = 1.125rem ect ect.

This way if someone has their font changed in their browser it wont completely break design by having some being relative units and some being hard coded pixel amounts

**Comment by sirikon** [comment]
Misunderstood the issue... :)

Totally agree, let's do that :)

**Comment by sirikon** [comment]
I'll close this, as this is now knowledge of all the collaborators and we agree.
